name: Devops Workflow Pedro

on:
  push:
    branches:
      - main

jobs:
  build: 
    runs-on: ubuntu-latest
    steps:
      - name: Checkout de Código
        uses: actions/checkout@v5
      - name: Build Aplicação
        run: echo "Estou buildando a Aplicação!"

  dev:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Fase de Desenvolvimento
        run: echo "Deploy no ambiente de Desenvolvimento!"

  qa:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: "Base de Teste e Qualidade"
        run: exit 1  # simula falha

  homologacao:
    runs-on: ubuntu-latest
    needs: [build, qa]
    steps:
      - name: "Ambiente de homologacao"
        run: echo "Executando Deploy em ambiente de homologacao!"

  producao:
    runs-on: ubuntu-latest
    needs: homologacao
    steps:
      - name: "Deploy Producao"
        run: echo "Executando Deploy em Producao!"

  send_email:
    runs-on: ubuntu-latest
    needs: [build, qa, homologacao]
    if: ${{ failure() }}  # dispara apenas se algum job falhar
    steps:
      - name: Enviar e-mail de falha
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.gmail.com
          server_port: 587
          username: ${{ secrets.SMTP_USER }}
          password: ${{ secrets.SMTP_PASS }}
          subject: "🚨 Falha no Workflow: Devops Workflow Pedro"
          to: "phpedrohc1967@gmail.com"
          from: "GitHub Actions <${{ secrets.SMTP_USER }}>"
          body: |
            O workflow falhou!

            Status dos jobs:
            - Build: ${{ needs.build.result }}
            - QA: ${{ needs.qa.result }}
            - Homologacao: ${{ needs.homologacao.result }}
