name: Devops Workflow Pedro

on:
  push:
    branches:
      - main

jobs:
  build: 
    runs-on: ubuntu-latest

    steps:
      - name: Checkout de Código
        uses: actions/checkout@v5

      - name: Mostrar Mensagem
        run: echo "Ola, Pedro Devops!"